Add new template to perform rollout of Deployment. Execute the script during cleanup only when prefixed with uninstall
Signed-off-by: cmoulliard <cmoulliard@redhat.com>

diff --git a/src/main/resources/templates/waitscript b/src/main/resources/templates/waitscript
--- a/src/main/resources/templates/waitscript
+++ b/src/main/resources/templates/waitscript
@@ -1,6 +1,27 @@
 {#let wait=step.waitCondition namespace=step.namespace}
-echo "Wait for {wait.endpoint.name} ready ..."
-until curl -ks {wait.endpoint.protocol}://{wait.endpoint.name}.{namespace.name}:{wait.endpoint.port}/{wait.path}; do
-  echo "Waiting for service to be ready..."
-  sleep 5
+
+TIMEOUT_SECONDS=180
+RETRY_INTERVAL=5
+ELAPSED_TIME=0
+
+URL="{wait.endpoint.protocol}://{wait.endpoint.name}.{namespace.name}:{wait.endpoint.port}/{wait.endpoint.path}"
+CMD="curl -i -o - -ks -X GET $URL -H \"Content-Type: application/json\""
+
+echo "Wait for $URL endpoint to be ready ..."
+
+while [ "$ELAPSED_TIME" -lt "$TIMEOUT_SECONDS" ]; do
+  STATUS=$($CMD | grep HTTP | awk '\{print $2\}')
+  if [ "$STATUS" != "200" ]; then
+    echo "Attempt failed. Status: $STATUS. Retrying in $RETRY_INTERVAL seconds..."
+    sleep $RETRY_INTERVAL
+    ELAPSED_TIME=$((ELAPSED_TIME + RETRY_INTERVAL))
+  else
+    echo "Endpoint replied successfully. (Status: $STATUS)"
+    exit 0
+  fi
 done
+
+echo "Error: endpoint failed after $TIMEOUT_SECONDS seconds. Service did not return HTTP 200 OK."
+echo "Service checked: $URL"
+exit 1
+{/let}
